CREATE TABLE users(
                      id INT generated by default as identity primary key,
                      username VARCHAR(50) NOT NULL,
                      password VARCHAR(100) NOT NULL,
                      first_name VARCHAR(50) NOT NULL,
                      last_name VARCHAR(50) NOT NULL,
                      phone VARCHAR(20) NOT NULL,
                      image VARCHAR(255),
                      role VARCHAR(20) NOT NULL,
                      enabled BOOLEAN
);

CREATE TABLE ads (
                     id SERIAL PRIMARY KEY,
                     author_id INTEGER REFERENCES users (id),
                     image VARCHAR(500),
                     price INTEGER NOT NULL,
                     title VARCHAR(100) NOT NULL,
                     description VARCHAR(1000)
);

CREATE TABLE comments (
                          id INT generated by default as identity primary key,
                          author_id INT NOT NULL,
                          author_image VARCHAR(255) NOT NULL,
                          author_first_name VARCHAR(255) NOT NULL,
                          created_at BIGINT NOT NULL,
                          text TEXT NOT NULL,
                          FOREIGN KEY (author_id) REFERENCES users (id)
);