CREATE TABLE users(
                      id BIGINT generated by default as identity primary key,
                      username VARCHAR(255) NOT NULL,
                      password VARCHAR(255) NOT NULL,
                      first_name VARCHAR(255) NOT NULL,
                      last_name VARCHAR(255) NOT NULL,
                      phone VARCHAR(255) NOT NULL,
                      image VARCHAR(255),
                      role VARCHAR(255) NOT NULL,
                      enabled BOOLEAN
);